

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  login-module: org.apache.kafka.common.security.plain.PlainLoginModule
  security-protocol: SASL_SSL
  sasl-mechanism: PLAIN
  client-id: locations-consumer-client-id
  username: ${KAFKA_USERNAME}
  password: ${KAFKA_PASSWORD}
  schema-registry:
    url: ${KAFKA_SCHEMA_REGISTRY_URL}
    username: ${KAFKA_SCHEMA_REGISTRY_API_KEY}
    password: ${KAFKA_SCHEMA_REGISTRY_PASSWORD}
  consumer:
    facilities:
      client-id: facilities-consumer
      topic: ${KAFKA_FACILITIES_TOPIC}
    locations:
      client-id: locations-consumer
      topic: ${KAFKA_LOCATIONS_TOPIC}
    consumer-group: ${KAFKA_CONSUMER_GROUP}
    offset-auto-reset: earliest
    concurrency: 1
    max-poll-records: 5
    max-poll-timeout: 5000
    max-fetch-size-bytes: 2097164
    retry:
      max-attempts: 3
      initial-interval-secs: 2

spring:
  application:
    name: locations-consumer
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    #  r2dbc:a-driver:pipes://localhost:3306/my_database?locale=en_US
    #  \___/ \______/ \___/   \____________/\__________/\___________/
    #  |       |      |           |           |           |
    #  scheme  driver  protocol  authority    path        query
    url: ${POSTGRES_SCHEME}:postgresql:${POSTGRES_HOST}/${POSTGRES_DB}?locale=en_GB
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PWD}
  profiles:
    active: ${PROFILE}
  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: ${OTEL_COLLECTOR_ADDRESS}
management:
  health:
    kafka:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,diskSpace,ping,kafka"
          show-details: always

  endpoints:
    web:
      exposure:
        include: health, info, prometheus
#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG
#    io.r2dbc.postgresql.PARAM: DEBUG
