CREATE TABLE GEOGRAPHY
(
	ID										uuid,
    GEO_ROW_ID                              VARCHAR (14),
    GEO_TYPE                                VARCHAR (20),
    NAME                                   	VARCHAR (512),
    STATUS                                 	VARCHAR (512),
    VALID_FROM                              TIMESTAMP,
    VALID_TO                                TIMESTAMP,
    LONGITUDE                              	VARCHAR (512),
    LATITUDE                               	VARCHAR (512),
    TIME_ZONE                               VARCHAR (20),
    DAYLIGHT_SAVING_TIME                   	VARCHAR (20),
    UTC_OFFSET_MINUTES                     	VARCHAR (20),
    DAYLIGHT_SAVING_START                   VARCHAR (25),
    DAYLIGHT_SAVING_END                     VARCHAR (25),
    DAYLIGHT_SAVING_SHIFT_MINUTES    		VARCHAR (20),
    DESCRIPTION                             VARCHAR (512),
    WORKAROUND_REASON                  		VARCHAR (512),
    RESTRICTED                              VARCHAR (512),
    POSTAL_CODE_MANDATORY_FLAG      		VARCHAR (20),
    STATE_PROVINCE_MANDATORY       			VARCHAR (20),
    DIALING_CODE                            VARCHAR (20),
    DIALING_CODE_DESCRIPTION            	VARCHAR (20),
    PORT_FLAG                               VARCHAR (20),
    OLSON_TIME_ZONE                         VARCHAR (20),
    BDA_TYPE                                VARCHAR (20),
    HSUD_NAME                            	VARCHAR (512));