---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: locations-geo-consumer
    app: locations-geo-consumer
    env: dev
    version: will-be-dynamically-updated
    product: synergy-reference-data
  name: locations-geo-consumer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      k8s-app: locations-geo-consumer
  template:
    metadata:
      labels:
        k8s-app: locations-geo-consumer
        app: locations-geo-consumer
        env: dev
        product: synergy-reference-data
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
        ad.datadoghq.com/locations-geo-consumer.check_names: '["openmetrics"]'
        ad.datadoghq.com/locations-geo-consumer.init_configs: '[{}]'
        ad.datadoghq.com/locations-geo-consumer.instances: '[{"prometheus_url": "http://%%host%%:8080/actuator/prometheus",
            "namespace": "#{datadog.namespace}#", "metrics": ["*"]}]'
        vault.security.banzaicloud.io/vault-role: will-be-dynamically-updated
    spec:
      imagePullSecrets:
        - name: reference-data-github-packages-pull
      containers:
        - image: application-container-image
          imagePullPolicy: Always
          name: locations-geo-consumer
          ports:
            - containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            periodSeconds: 10
            initialDelaySeconds: 30

          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE_NAME
              value: locations-geo-consumer
            - name: DD_LOG_LEVEL
              value: "#{datadog.debug.level}#"
            - name: DD_ENV
              value: "#{datadog.env}#"
            - name: DD_APM_ENABLED
              value: "#{datadog.enabled}#"
            - name: OTEL_COLLECTOR_ADDRESS
              value: vault:synergyreferencedata-kv/data/readable/dev/services/otel-collector/address#address
            - name: PROFILE
              value: vault:synergyreferencedata-kv/data/readable/dev/services/locations-consumer/profile#profile
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: vault:synergyreferencedata-kv/data/readable/dev/services/locations-consumer/kafka/bootstrap-servers#bootstrap-servers
            - name: KAFKA_USERNAME
              value: vault:synergyreferencedata-kv/data/readable/dev/services/locations-consumer/kafka/shipment/username#username
            - name: KAFKA_PASSWORD
              value: vault:synergyreferencedata-kv/data/dev/services/locations-consumer/kafka/password#password
            - name: KAFKA_CONSUMER_GROUP
              value: vault:synergyreferencedata-kv/data/readable/dev/services/locations-consumer/kafka/consumer-group#consumer-group
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: vault:synergyreferencedata-kv/data/readable/dev/services/locations-consumer/kafka/schema-registry/url#url
            - name: KAFKA_SCHEMA_REGISTRY_API_KEY
              value: vault:synergyreferencedata-kv/data/readable/dev/services/locations-consumer/kafka/schema-registry/api-key#api-key
            - name: KAFKA_SCHEMA_REGISTRY_PASSWORD
              value: vault:synergyreferencedata-kv/data/dev/services/locations-consumer/kafka/schema-registry/password#password
            - name: ELASTICSEARCH_HOST
              value: vault:synergyreferencedata-kv/data/readable/dev/services/locations-consumer/elasticsearch/host#host
            - name: ELASTICSEARCH_API_KEY
              value: vault:synergyreferencedata-kv/data/dev/services/locations-consumer/elasticsearch/api-key#api-key

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi