/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.facility.smds.operations.msk;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Facility OpeningHours */
@org.apache.avro.specific.AvroGenerated
public class openingHour extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4778990993205621486L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"openingHour\",\"namespace\":\"com.maersk.facility.smds.operations.msk\",\"doc\":\"Facility OpeningHours\",\"fields\":[{\"name\":\"day\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The operational and commercial facility opening day information. Example: Monday\"},{\"name\":\"openTimeHours\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The operational and commercial facility opening time hours information. Example: 8\"},{\"name\":\"openTimeMinutes\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The operational and commercial facility opening time minutes information. Example: 30\"},{\"name\":\"closeTimeHours\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The operational and commercial facility closing time hours information. Example: 17\"},{\"name\":\"closeTimeMinutes\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The operational and commercial facility closing time minutes information. Example: 30\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<openingHour> ENCODER =
      new BinaryMessageEncoder<openingHour>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<openingHour> DECODER =
      new BinaryMessageDecoder<openingHour>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<openingHour> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<openingHour> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<openingHour> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<openingHour>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this openingHour to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a openingHour from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a openingHour instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static openingHour fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The operational and commercial facility opening day information. Example: Monday */
  private java.lang.String day;
  /** The operational and commercial facility opening time hours information. Example: 8 */
  private java.lang.String openTimeHours;
  /** The operational and commercial facility opening time minutes information. Example: 30 */
  private java.lang.String openTimeMinutes;
  /** The operational and commercial facility closing time hours information. Example: 17 */
  private java.lang.String closeTimeHours;
  /** The operational and commercial facility closing time minutes information. Example: 30 */
  private java.lang.String closeTimeMinutes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public openingHour() {}

  /**
   * All-args constructor.
   * @param day The operational and commercial facility opening day information. Example: Monday
   * @param openTimeHours The operational and commercial facility opening time hours information. Example: 8
   * @param openTimeMinutes The operational and commercial facility opening time minutes information. Example: 30
   * @param closeTimeHours The operational and commercial facility closing time hours information. Example: 17
   * @param closeTimeMinutes The operational and commercial facility closing time minutes information. Example: 30
   */
  public openingHour(java.lang.String day, java.lang.String openTimeHours, java.lang.String openTimeMinutes, java.lang.String closeTimeHours, java.lang.String closeTimeMinutes) {
    this.day = day;
    this.openTimeHours = openTimeHours;
    this.openTimeMinutes = openTimeMinutes;
    this.closeTimeHours = closeTimeHours;
    this.closeTimeMinutes = closeTimeMinutes;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return day;
    case 1: return openTimeHours;
    case 2: return openTimeMinutes;
    case 3: return closeTimeHours;
    case 4: return closeTimeMinutes;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: day = value$ != null ? value$.toString() : null; break;
    case 1: openTimeHours = value$ != null ? value$.toString() : null; break;
    case 2: openTimeMinutes = value$ != null ? value$.toString() : null; break;
    case 3: closeTimeHours = value$ != null ? value$.toString() : null; break;
    case 4: closeTimeMinutes = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'day' field.
   * @return The operational and commercial facility opening day information. Example: Monday
   */
  public java.lang.String getDay() {
    return day;
  }


  /**
   * Sets the value of the 'day' field.
   * The operational and commercial facility opening day information. Example: Monday
   * @param value the value to set.
   */
  public void setDay(java.lang.String value) {
    this.day = value;
  }

  /**
   * Gets the value of the 'openTimeHours' field.
   * @return The operational and commercial facility opening time hours information. Example: 8
   */
  public java.lang.String getOpenTimeHours() {
    return openTimeHours;
  }


  /**
   * Sets the value of the 'openTimeHours' field.
   * The operational and commercial facility opening time hours information. Example: 8
   * @param value the value to set.
   */
  public void setOpenTimeHours(java.lang.String value) {
    this.openTimeHours = value;
  }

  /**
   * Gets the value of the 'openTimeMinutes' field.
   * @return The operational and commercial facility opening time minutes information. Example: 30
   */
  public java.lang.String getOpenTimeMinutes() {
    return openTimeMinutes;
  }


  /**
   * Sets the value of the 'openTimeMinutes' field.
   * The operational and commercial facility opening time minutes information. Example: 30
   * @param value the value to set.
   */
  public void setOpenTimeMinutes(java.lang.String value) {
    this.openTimeMinutes = value;
  }

  /**
   * Gets the value of the 'closeTimeHours' field.
   * @return The operational and commercial facility closing time hours information. Example: 17
   */
  public java.lang.String getCloseTimeHours() {
    return closeTimeHours;
  }


  /**
   * Sets the value of the 'closeTimeHours' field.
   * The operational and commercial facility closing time hours information. Example: 17
   * @param value the value to set.
   */
  public void setCloseTimeHours(java.lang.String value) {
    this.closeTimeHours = value;
  }

  /**
   * Gets the value of the 'closeTimeMinutes' field.
   * @return The operational and commercial facility closing time minutes information. Example: 30
   */
  public java.lang.String getCloseTimeMinutes() {
    return closeTimeMinutes;
  }


  /**
   * Sets the value of the 'closeTimeMinutes' field.
   * The operational and commercial facility closing time minutes information. Example: 30
   * @param value the value to set.
   */
  public void setCloseTimeMinutes(java.lang.String value) {
    this.closeTimeMinutes = value;
  }

  /**
   * Creates a new openingHour RecordBuilder.
   * @return A new openingHour RecordBuilder
   */
  public static com.maersk.facility.smds.operations.msk.openingHour.Builder newBuilder() {
    return new com.maersk.facility.smds.operations.msk.openingHour.Builder();
  }

  /**
   * Creates a new openingHour RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new openingHour RecordBuilder
   */
  public static com.maersk.facility.smds.operations.msk.openingHour.Builder newBuilder(com.maersk.facility.smds.operations.msk.openingHour.Builder other) {
    if (other == null) {
      return new com.maersk.facility.smds.operations.msk.openingHour.Builder();
    } else {
      return new com.maersk.facility.smds.operations.msk.openingHour.Builder(other);
    }
  }

  /**
   * Creates a new openingHour RecordBuilder by copying an existing openingHour instance.
   * @param other The existing instance to copy.
   * @return A new openingHour RecordBuilder
   */
  public static com.maersk.facility.smds.operations.msk.openingHour.Builder newBuilder(com.maersk.facility.smds.operations.msk.openingHour other) {
    if (other == null) {
      return new com.maersk.facility.smds.operations.msk.openingHour.Builder();
    } else {
      return new com.maersk.facility.smds.operations.msk.openingHour.Builder(other);
    }
  }

  /**
   * RecordBuilder for openingHour instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<openingHour>
    implements org.apache.avro.data.RecordBuilder<openingHour> {

    /** The operational and commercial facility opening day information. Example: Monday */
    private java.lang.String day;
    /** The operational and commercial facility opening time hours information. Example: 8 */
    private java.lang.String openTimeHours;
    /** The operational and commercial facility opening time minutes information. Example: 30 */
    private java.lang.String openTimeMinutes;
    /** The operational and commercial facility closing time hours information. Example: 17 */
    private java.lang.String closeTimeHours;
    /** The operational and commercial facility closing time minutes information. Example: 30 */
    private java.lang.String closeTimeMinutes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.facility.smds.operations.msk.openingHour.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.day)) {
        this.day = data().deepCopy(fields()[0].schema(), other.day);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.openTimeHours)) {
        this.openTimeHours = data().deepCopy(fields()[1].schema(), other.openTimeHours);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.openTimeMinutes)) {
        this.openTimeMinutes = data().deepCopy(fields()[2].schema(), other.openTimeMinutes);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.closeTimeHours)) {
        this.closeTimeHours = data().deepCopy(fields()[3].schema(), other.closeTimeHours);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.closeTimeMinutes)) {
        this.closeTimeMinutes = data().deepCopy(fields()[4].schema(), other.closeTimeMinutes);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing openingHour instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.facility.smds.operations.msk.openingHour other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.day)) {
        this.day = data().deepCopy(fields()[0].schema(), other.day);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.openTimeHours)) {
        this.openTimeHours = data().deepCopy(fields()[1].schema(), other.openTimeHours);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.openTimeMinutes)) {
        this.openTimeMinutes = data().deepCopy(fields()[2].schema(), other.openTimeMinutes);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.closeTimeHours)) {
        this.closeTimeHours = data().deepCopy(fields()[3].schema(), other.closeTimeHours);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.closeTimeMinutes)) {
        this.closeTimeMinutes = data().deepCopy(fields()[4].schema(), other.closeTimeMinutes);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'day' field.
      * The operational and commercial facility opening day information. Example: Monday
      * @return The value.
      */
    public java.lang.String getDay() {
      return day;
    }


    /**
      * Sets the value of the 'day' field.
      * The operational and commercial facility opening day information. Example: Monday
      * @param value The value of 'day'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder setDay(java.lang.String value) {
      validate(fields()[0], value);
      this.day = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'day' field has been set.
      * The operational and commercial facility opening day information. Example: Monday
      * @return True if the 'day' field has been set, false otherwise.
      */
    public boolean hasDay() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'day' field.
      * The operational and commercial facility opening day information. Example: Monday
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder clearDay() {
      day = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'openTimeHours' field.
      * The operational and commercial facility opening time hours information. Example: 8
      * @return The value.
      */
    public java.lang.String getOpenTimeHours() {
      return openTimeHours;
    }


    /**
      * Sets the value of the 'openTimeHours' field.
      * The operational and commercial facility opening time hours information. Example: 8
      * @param value The value of 'openTimeHours'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder setOpenTimeHours(java.lang.String value) {
      validate(fields()[1], value);
      this.openTimeHours = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'openTimeHours' field has been set.
      * The operational and commercial facility opening time hours information. Example: 8
      * @return True if the 'openTimeHours' field has been set, false otherwise.
      */
    public boolean hasOpenTimeHours() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'openTimeHours' field.
      * The operational and commercial facility opening time hours information. Example: 8
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder clearOpenTimeHours() {
      openTimeHours = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'openTimeMinutes' field.
      * The operational and commercial facility opening time minutes information. Example: 30
      * @return The value.
      */
    public java.lang.String getOpenTimeMinutes() {
      return openTimeMinutes;
    }


    /**
      * Sets the value of the 'openTimeMinutes' field.
      * The operational and commercial facility opening time minutes information. Example: 30
      * @param value The value of 'openTimeMinutes'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder setOpenTimeMinutes(java.lang.String value) {
      validate(fields()[2], value);
      this.openTimeMinutes = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'openTimeMinutes' field has been set.
      * The operational and commercial facility opening time minutes information. Example: 30
      * @return True if the 'openTimeMinutes' field has been set, false otherwise.
      */
    public boolean hasOpenTimeMinutes() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'openTimeMinutes' field.
      * The operational and commercial facility opening time minutes information. Example: 30
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder clearOpenTimeMinutes() {
      openTimeMinutes = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'closeTimeHours' field.
      * The operational and commercial facility closing time hours information. Example: 17
      * @return The value.
      */
    public java.lang.String getCloseTimeHours() {
      return closeTimeHours;
    }


    /**
      * Sets the value of the 'closeTimeHours' field.
      * The operational and commercial facility closing time hours information. Example: 17
      * @param value The value of 'closeTimeHours'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder setCloseTimeHours(java.lang.String value) {
      validate(fields()[3], value);
      this.closeTimeHours = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'closeTimeHours' field has been set.
      * The operational and commercial facility closing time hours information. Example: 17
      * @return True if the 'closeTimeHours' field has been set, false otherwise.
      */
    public boolean hasCloseTimeHours() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'closeTimeHours' field.
      * The operational and commercial facility closing time hours information. Example: 17
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder clearCloseTimeHours() {
      closeTimeHours = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'closeTimeMinutes' field.
      * The operational and commercial facility closing time minutes information. Example: 30
      * @return The value.
      */
    public java.lang.String getCloseTimeMinutes() {
      return closeTimeMinutes;
    }


    /**
      * Sets the value of the 'closeTimeMinutes' field.
      * The operational and commercial facility closing time minutes information. Example: 30
      * @param value The value of 'closeTimeMinutes'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder setCloseTimeMinutes(java.lang.String value) {
      validate(fields()[4], value);
      this.closeTimeMinutes = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'closeTimeMinutes' field has been set.
      * The operational and commercial facility closing time minutes information. Example: 30
      * @return True if the 'closeTimeMinutes' field has been set, false otherwise.
      */
    public boolean hasCloseTimeMinutes() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'closeTimeMinutes' field.
      * The operational and commercial facility closing time minutes information. Example: 30
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.msk.openingHour.Builder clearCloseTimeMinutes() {
      closeTimeMinutes = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public openingHour build() {
      try {
        openingHour record = new openingHour();
        record.day = fieldSetFlags()[0] ? this.day : (java.lang.String) defaultValue(fields()[0]);
        record.openTimeHours = fieldSetFlags()[1] ? this.openTimeHours : (java.lang.String) defaultValue(fields()[1]);
        record.openTimeMinutes = fieldSetFlags()[2] ? this.openTimeMinutes : (java.lang.String) defaultValue(fields()[2]);
        record.closeTimeHours = fieldSetFlags()[3] ? this.closeTimeHours : (java.lang.String) defaultValue(fields()[3]);
        record.closeTimeMinutes = fieldSetFlags()[4] ? this.closeTimeMinutes : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<openingHour>
    WRITER$ = (org.apache.avro.io.DatumWriter<openingHour>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<openingHour>
    READER$ = (org.apache.avro.io.DatumReader<openingHour>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.day);

    out.writeString(this.openTimeHours);

    out.writeString(this.openTimeMinutes);

    out.writeString(this.closeTimeHours);

    out.writeString(this.closeTimeMinutes);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.day = in.readString();

      this.openTimeHours = in.readString();

      this.openTimeMinutes = in.readString();

      this.closeTimeHours = in.readString();

      this.closeTimeMinutes = in.readString();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.day = in.readString();
          break;

        case 1:
          this.openTimeHours = in.readString();
          break;

        case 2:
          this.openTimeMinutes = in.readString();
          break;

        case 3:
          this.closeTimeHours = in.readString();
          break;

        case 4:
          this.closeTimeMinutes = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










