CREATE TABLE GEO_ALTERNATE_CODE_LINKS
(
    ID                                  UUID,
    GEO_ID                             	VARCHAR (14),
    ALTERNATE_CODE_ID                   VARCHAR (100),
    ALTERNATE_CODE_TYPE                 VARCHAR (100)
    CONSTRAINT GEO_ALTERNATE_CODE_LINKS_PK PRIMARY KEY (ID),
    CONSTRAINT GEO_ALTERNATE_CODE_LINKS_FK
    FOREIGN KEY(GEO_ID)
    REFERENCES GEOGRAPHY(GEO_ID)
    ON DELETE CASCADE);