CREATE TABLE FACILITY_SERVICES
(
    ID                                   VARCHAR (50),
    FACILITY_ID                          VARCHAR (50),
    SERVICE_NAME                         VARCHAR (100),
    SERVICE_CODE                         VARCHAR (100),
    SERVICE_DESCRIPTION                  VARCHAR (100),
    VALID_THROUGH_DATE                   TIMESTAMP,
    CONSTRAINT FACILITY_SERVICES_PK PRIMARY KEY (ID),
    CONSTRAINT FACILITY_FK FOREIGN KEY(FACILITY_ID)
    REFERENCES FACILITIES(ID)
    ON DELETE CASCADE);

-- CREATE INDEX IF NOT EXISTS FACILITY_SERVICES_IDX ON FACILITY_SERVICES (SERVICE_NAME);