CREATE TABLE FACILITY_ALTERNATE_CODE_LINKS
(
    FACILITY_ID                        	VARCHAR (14),
    ALTERNATE_CODE_ID                   VARCHAR (100),
    PRIMARY KEY (FACILITY_ID, ALTERNATE_CODE_ID));