CREATE TABLE FENCES
(
    ID                VARCHAR (50),
    FACILITY_ID       VARCHAR (50),
    NAME              VARCHAR (50),
    FENCE_TYPE        VARCHAR (100),
    CONSTRAINT FENCES_PK PRIMARY KEY (ID),
    CONSTRAINT FACILITY_FK FOREIGN KEY(FACILITY_ID)
    REFERENCES FACILITIES(ID)
    ON DELETE CASCADE);

CREATE INDEX IF NOT EXISTS FENCES_IDX ON FENCES (FENCE_TYPE);
CREATE INDEX IF NOT EXISTS FENCES_FACILITY_IDX ON FENCES (FACILITY_ID);