CREATE TABLE OPENING_HOURS
(
    ID                              VARCHAR (50),
    FACILITY_ID                     VARCHAR (50),
    DAY                             VARCHAR (20),
    OPEN_TIME_HOURS                 VARCHAR (100),
    OPEN_TIME_MINUTES               VARCHAR (100),
    CLOSE_TIME_HOURS                VARCHAR (100),
    CLOSE_TIME_MINUTES              VARCHAR (100),
    CONSTRAINT OPENING_HOURS_PK PRIMARY KEY (ID),
    CONSTRAINT FACILITY_FK FOREIGN KEY(FACILITY_ID)
    REFERENCES FACILITIES(ID)
    ON DELETE CASCADE);

-- CREATE INDEX IF NOT EXISTS OPENING_HOURS_IDX ON OPENING_HOURS (???);