CREATE TABLE TRANSPORT_MODES
(
    ID                             VARCHAR (50),
    FACILITY_ID                    VARCHAR (50),
    MODE_OF_TRANSPORT              VARCHAR (50),
    TRANSPORT_CODE                 VARCHAR (100),
    TRANSPORT_DESCRIPTION          VARCHAR (100),
    VALID_THROUGH_DATE             TIMESTAMP,
    CONSTRAINT TRANSPORT_MODES_PK PRIMARY KEY (ID),
    CONSTRAINT FACILITY_FK FOREIGN KEY(FACILITY_ID)
    REFERENCES FACILITIES(ID)
    ON DELETE CASCADE);

-- CREATE INDEX IF NOT EXISTS TRANSPORT_MODES_IDX ON TRANSPORT_MODES (MODE_OF_TRANSPORT);