on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

name: Build Helm chart

jobs:
  build:
    name: Build and push Helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - uses: Maersk-Global/github-actions-commons/helm-build-push@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}