on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pom.xml'
      - 'src/**'

name: Build and push Docker image

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Checkout common actions
        uses: actions/checkout@v2
        with:
          repository: maersk-global/github-actions-commons
          token: ${{ secrets.ACCESS_TOKEN }}
          path: .github/actions/commons
      - name: Maven build
        uses: ./.github/actions/commons/maven-build
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          jdkVersion: 17
          jdkDistribution: temurin
      - uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: ${{ github.workspace }}

  sonarqube:
    name: SonarQube scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: Checkout common actions
        uses: actions/checkout@v2
        with:
          repository: maersk-global/github-actions-commons
          token: ${{ secrets.ACCESS_TOKEN }}
          path: .github/actions/commons
      - uses: ./.github/actions/commons/sonarqube-scan
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          host: ${{ secrets.MDN_SONARQUBE_HOST }}
          token: ${{ secrets.MDN_SONARQUBE_TOKEN }}
          jdkVersion: 17
          jdkDistribution: temurin

  blackduck:
    name: Blackduck scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: Checkout common actions
        uses: actions/checkout@v2
        with:
          repository: maersk-global/github-actions-commons
          token: ${{ secrets.ACCESS_TOKEN }}
          path: .github/actions/commons
      - uses: ./.github/actions/commons/blackduck-scan
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          url: ${{ secrets.BLACKDUCK_URL }}
          apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}

  polaris:
    name: Polaris scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: Checkout common actions
        uses: actions/checkout@v2
        with:
          repository: maersk-global/github-actions-commons
          token: ${{ secrets.ACCESS_TOKEN }}
          path: .github/actions/commons
      - uses: ./.github/actions/commons/polaris-scan
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          apiToken: ${{ secrets.POLARIS_API_TOKEN }}
          serverUrl: ${{ secrets.POLARIS_SERVER_URL }}

  docker_image:
    name: Building a docker image
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: workspace
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
      - name: Build with Maven
        run: |
          mvn spring-boot:build-image -B -e -Dspring-boot.build-image.imageName=ghcr.io/maersk-global/locations-consumer:${{ github.run_id }}
          docker images
          docker save ghcr.io/maersk-global/locations-consumer:${{ github.run_id }} > /tmp/locations.tar
          ls /tmp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: /tmp/locations.tar

          
  docker_push:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: docker_image
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docker-image
      - name: Checkout common actions
        uses: actions/checkout@v2
        with:
          repository: maersk-global/github-actions-commons
          token: ${{ secrets.ACCESS_TOKEN }}
          path: .github/actions/commons
      - name: Push Docker image
        uses: ./.github/actions/commons/docker-push
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}