on:
  workflow_dispatch:
    inputs:
      dockerImage:
        description: Docker image
        required: false
      dockerImageVersion:
        description: Docker image version
        required: false
      helmChart:
        description: Helm chart
        required: false
      helmChartVersion:
        description: Helm chart version
        required: false
name: Deploy to Kubernetes
jobs:
  prepare:
    name: Prepare deployment
    runs-on: ubuntu-latest
    outputs:
      dockerImage: ${{ steps.prepare-deployment.outputs.dockerImage }}
      dockerImageVersion: ${{ steps.prepare-deployment.outputs.dockerImageVersion }}
      helmChart: ${{ steps.prepare-deployment.outputs.helmChart }}
      helmChartVersion: ${{ steps.prepare-deployment.outputs.helmChartVersion }}
    steps:
      - id: prepare-deployment
        name: Prepare deployment
        uses: Maersk-Global/github-actions-commons/prepare-deployment@main
        with:
          githubToken: ${{ secrets.ACCESS_TOKEN }}
          dockerImage: ${{ github.event.inputs.dockerImage }}
          helmChart: ${{ github.event.inputs.helmChart }}

  deploy-dev-emea:
    name: Dev (EMEA)
    environment: dev-emea
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Helm install
        uses: Maersk-Global/github-actions-commons/helm-upgrade@main
        with:
          helmChart: ${{ needs.prepare.outputs.helmChart }}
          helmChartVersion: ${{ needs.prepare.outputs.helmChartVersion }}
          dockerImage: ${{ needs.prepare.outputs.dockerImage }}
          dockerImageVersion: ${{ needs.prepare.outputs.dockerImageVersion }}
          helmValues: ./helm/chart/values/westeurope/dev/values.yml
          registryPassword: ${{ secrets.GHCR_PULL_TOKEN }}
          k8s-cluster: mcom-np-west-1
          k8s-namespace: reference-data-dev
          vaultName: ${{ secrets.VAULT_NAME }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultRoleSecretId: ${{ secrets.VAULT_ROLE_SECRET_ID }}

  deploy-dev-apac:
    name: Dev (APAC)
    environment: dev-apac
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Helm install
        uses: Maersk-Global/github-actions-commons/helm-upgrade@main
        with:
          helmChart: ${{ needs.prepare.outputs.helmChart }}
          helmChartVersion: ${{ needs.prepare.outputs.helmChartVersion }}
          dockerImage: ${{ needs.prepare.outputs.dockerImage }}
          dockerImageVersion: ${{ needs.prepare.outputs.dockerImageVersion }}
          helmValues: ./helm/chart/values/japaneast/dev/values.yml
          registryPassword: ${{ secrets.GHCR_PULL_TOKEN }}
          k8s-cluster: core-dev-japaneast-1
          k8s-namespace: reference-data-dev
          vaultName: ${{ secrets.VAULT_NAME }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultRoleSecretId: ${{ secrets.VAULT_ROLE_SECRET_ID }}

  deploy-preprod-emea:
    name: Preprod (EMEA)
    environment: preprod-emea
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Helm install
        uses: Maersk-Global/github-actions-commons/helm-upgrade@main
        with:
          helmChart: ${{ needs.prepare.outputs.helmChart }}
          helmChartVersion: ${{ needs.prepare.outputs.helmChartVersion }}
          dockerImage: ${{ needs.prepare.outputs.dockerImage }}
          dockerImageVersion: ${{ needs.prepare.outputs.dockerImageVersion }}
          helmValues: ./helm/chart/values/westeurope/preprod/values.yml
          registryPassword: ${{ secrets.GHCR_PULL_TOKEN }}
          k8s-cluster: mcom-np-west-1
          k8s-namespace: reference-data-preprod
          vaultName: ${{ secrets.VAULT_NAME }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultRoleSecretId: ${{ secrets.VAULT_ROLE_SECRET_ID }}

  deploy-preprod-apac:
    name: Preprod (APAC)
    environment: preprod-apac
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Helm install
        uses: Maersk-Global/github-actions-commons/helm-upgrade@main
        with:
          helmChart: ${{ needs.prepare.outputs.helmChart }}
          helmChartVersion: ${{ needs.prepare.outputs.helmChartVersion }}
          dockerImage: ${{ needs.prepare.outputs.dockerImage }}
          dockerImageVersion: ${{ needs.prepare.outputs.dockerImageVersion }}
          helmValues: ./helm/chart/values/japaneast/preprod/values.yml
          registryPassword: ${{ secrets.GHCR_PULL_TOKEN }}
          k8s-cluster: core-dev-japaneast-1
          k8s-namespace: reference-data-preprod
          vaultName: ${{ secrets.VAULT_NAME }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultRoleSecretId: ${{ secrets.VAULT_ROLE_SECRET_ID }}

  deploy-prod-emea:
    name: Prod (EMEA)
    environment: prod-emea
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Helm install
        uses: Maersk-Global/github-actions-commons/helm-upgrade@main
        with:
          helmChart: ${{ needs.prepare.outputs.helmChart }}
          helmChartVersion: ${{ needs.prepare.outputs.helmChartVersion }}
          dockerImage: ${{ needs.prepare.outputs.dockerImage }}
          dockerImageVersion: ${{ needs.prepare.outputs.dockerImageVersion }}
          helmValues: ./helm/chart/values/westeurope/prod/values.yml
          registryPassword: ${{ secrets.GHCR_PULL_TOKEN }}
          k8s-cluster: mcom-prod-westeurope-1
          k8s-namespace: reference-data
          vaultName: ${{ secrets.VAULT_NAME }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultRoleSecretId: ${{ secrets.VAULT_ROLE_SECRET_ID }}

  deploy-prod-apac:
    name: Prod (APAC)
    environment: prod-apac
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: Helm install
        uses: Maersk-Global/github-actions-commons/helm-upgrade@main
        with:
          helmChart: ${{ needs.prepare.outputs.helmChart }}
          helmChartVersion: ${{ needs.prepare.outputs.helmChartVersion }}
          dockerImage: ${{ needs.prepare.outputs.dockerImage }}
          dockerImageVersion: ${{ needs.prepare.outputs.dockerImageVersion }}
          helmValues: ./helm/chart/values/japaneast/prod/values.yml
          registryPassword: ${{ secrets.GHCR_PULL_TOKEN }}
          k8s-cluster: core-prod-japaneast-1
          k8s-namespace: reference-data-prod
          vaultName: ${{ secrets.VAULT_NAME }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultRoleSecretId: ${{ secrets.VAULT_ROLE_SECRET_ID }}